### ISSUE TITLE
make up `token-manager' pallet

### ISSUE THREAD

**Issue by energyGiver** [InfraBlockchain/infra-substrate#30]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

Relaychain needs a mapping link the AssetId between relay chain and each parachain.

### Request

features of `token-manager`pallet
- set SystemTokenTable
- insert the mapping link between chains to  SystemTokenTable

### Are you willing to help with this request?

Yes!

**Comment by cocoyoon** [comment]
author = "blockchain labs" 인 pallet 은 
prefix `infra-*` 통일하는것이 좋을거같습니다. 개인적으로는 `infra-system-token-pallet`

**Comment by energyGiver** [comment]
closed as it is merged
